[package]
name = "ThreadVille"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.24.1"
signal-stack = "0.1.0"
ncurses = "5.101.0"
libc = "0.2.126"